name: release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KFH: ${{secrets.KFH}}
      URL: ${{secrets.URL}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start
        run: ./start.sh
